### ISSUE TITLE
Picovoice Documentation Issue (/docs/quick-start/orca-python/)

### ISSUE THREAD

**Issue by bricelb** [Picovoice/orca#15]
I could not make this instruction work : 
orca.synthesize_to_file(text='${TEXT}', path='${WAV_OUTPUT_PATH}')
Is it already implemented ?

**Comment by laves** [comment]
Yes, you can see more detailed info in the [api docs](https://picovoice.ai/docs/api/orca-python/#pvorcaorcasynthesize_to_file)

**Comment by Din96Boy** [comment]
I'm testing this in python 
for me I had to change the function from 
`orca.synthesize_to_file(text='${TEXT}', path='${WAV_OUTPUT_PATH}')`

when I run the function like this it gives me an TypeError
`TypeError: Orca.synthesize_to_file() got an unexpected keyword argument 'path'`

so I had to change the code format
to
`orca.synthesize_to_file(text='${TEXT}', output_path='${WAV_OUTPUT_PATH}')
`
