### ISSUE TITLE
[Request] Go binding & demo

### ISSUE THREAD

**Issue by voidastro4** [Picovoice/orca#18]
It would be nice to have Go bindings & demo similar to other projects form picovoice

Deployment with python is inferior to Go for our team.

Thanks.

**Comment by ErisMik** [comment]
Hi @voidastro4, if this is for a commercial product you can reach out to your sales contact at Picovoice, or otherwise [contact us](https://picovoice.ai/pricing/) through sales to get the feature added. We also take community PRs.
