### ISSUE TITLE
Param to set Sample Rate?

### ISSUE THREAD

**Issue by patricker** [Picovoice/orca#38]
I'm trying to use Orca in an 8-bit u-law 8khz streaming use case (Twilio). I've done some 16-bit to 8-bit conversion w/ downsampling, and it's OK, but It would be nice to just do the 16-bit to 8-bit conversion (or even not that?)

Are there any parameters that can be exposed (I'm using NodeJS) to allow controlling the audio output format?

**Comment by bejager** [comment]
Hi @patricker , 
at the moment we don't provide an option to change the output format. However, you can directly get the raw PCM, which you can convert as you wish and then save in your desired format.
