### ISSUE TITLE
Orca Issue: Is Italian supported?

### ISSUE THREAD

**Issue by StefanoGiu** [Picovoice/orca#8]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Orca docs
- [X] I have searched the existing issues for Orca

### SDK

Python

### Orca package version

latest

### Framework version

Python 3.12

### Platform

Windows (x86_64)

### OS/Browser version

Windows 11

### Describe the bug

Is Italian supported?

### Steps To Reproduce

Is Italian supported?

### Expected Behavior

Is Italian supported?

**Comment by ErisMik** [comment]
Unfortunately Orca is English only at this time. Support for additional languages may come in the future but I cannot give a timeline for that.
